# Generated by Django 3.2.9 on 2021-11-08 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devcordenadas', '0002_auto_20211108_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageprojects',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_image', to='devcordenadas.projectspage'),
        ),
    ]
